create table users
(
    id                serial
        primary key,
    username          varchar(255) not null,
    password          varchar(255) not null,
    email             varchar(255) not null
        unique,
    address           text,
    is_confirmed      boolean default false,
    roles             text[],
    verification_code varchar(6)   not null,
    phone             varchar(16)
);

alter table users
    owner to postgres;

create table products
(
    id          serial
        primary key,
    name        varchar(255)   not null,
    description text,
    price       numeric(10, 2) not null,
    image_url   text
);

alter table products
    owner to postgres;

create table orders
(
    id      serial
        primary key,
    user_id bigint      not null
        references users,
    status  varchar(50) not null
);

alter table orders
    owner to postgres;

create table order_products
(
    order_id   bigint not null
        references orders,
    product_id bigint not null
        references products,
    quantity   integer default 1,
    id         serial,
    primary key (order_id, product_id)
);

alter table order_products
    owner to postgres;

